### ISSUE TITLE
pngquant is not thread-safe

### ISSUE THREAD

**Issue by erezarnon** [Brightcells/pngquant#1]
Compress multiple images in threads. They overwrite each other.

**Comment by agargara** [comment]
Ran into the same issue. Workaround seems to be to use a different tmp_file for each thread. e.g.: 

    pngquant.config(tmp_file='unique_filename')

**Comment by Brightcells** [comment]
Change to generate tmp file random https://github.com/Brightcells/pngquant/commit/6ed0525056a5ce943bb3826cd29bc09f0edcae12
